version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: reservationDB
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: "reservationApp"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    ports:
      - "3306:3306"
    # volumes:
    #   - ./data:/var/lib/mysql
